services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/todo_api
    ports:
      - "8000:8000"
    env_file:
      - Docker/env/.env.dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    depends_on:
      - web
