# Generated by Django 5.1.6 on 2025-03-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priorities', '0002_alter_priority_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
    ]
