# Generated by Django 5.1.6 on 2025-03-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
